# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Fe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fe

  target 'FeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeUITests' do
    # Pods for testing
  end

  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Analytics'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'

end
