# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Fe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fe
  pod 'Firebase/Analytics'
  pod 'Firebase'
  pod 'FirebaseUI'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Google'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'CorePlot'

  target 'FeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeUITests' do
    # Pods for testing
  end

end
